server:
  port: 8761
eureka:
  instance:
    hostname: CentOS
    prefer-ip-address: true # 显示ip信息
    ip-address: 120.79.11.150
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
